#!/bin/bash

# don't run this locally on your dev machine,
# it's supposed to be run on the signaller server in the cloud

source $HOME/.nvm/nvm.sh

cp $HOME/.env.prod $HOME/app/.env.prod
cd $HOME/app
npm ci --omit=dev
pm2 delete app
pm2 start "FORCE_COLOR=1 node --env-file=.env.prod x/signaller/server.js" --name app

